import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { ContentExamplesSection } from "@/components/home/ContentExamplesSection";
import { SeoFaqSection } from "@/components/home/SeoFaqSection";
import { WhatGitLoudDoesSection } from "@/components/home/WhatGitLoudDoesSection";

export const metadata: Metadata = {
  title: "GitHub PR Summary Examples",
  description:
    "See examples of GitHub pull request summaries, developer changelog entries, and social posts generated from public code changes.",
  alternates: {
    canonical: "/examples",
  },
  openGraph: {
    title: "GitHub PR Summary Examples",
    description:
      "Example PR summaries, changelog notes, portfolio bullets, and developer social posts generated by GitLoud.",
    url: "/examples",
  },
};

export default function ExamplesPage() {
  return (
    <main className="min-h-dvh">
      <Header />
      <section className="px-4 py-10 sm:px-6 lg:px-20 lg:py-14">
        <div className="mx-auto max-w-6xl space-y-4">
          <p className="text-sm font-semibold">GITLOUD EXAMPLES</p>
          <h1 className="max-w-3xl text-3xl font-bold tracking-tight sm:text-5xl">
            GitHub PR summaries and developer posts examples
          </h1>
          <p className="max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">
            Use these examples to understand the kind of summaries, changelog
            entries, portfolio bullets, and social posts GitLoud creates from
            public pull requests and commits.
          </p>
        </div>
      </section>
      <WhatGitLoudDoesSection/>
      <ContentExamplesSection />
      <SeoFaqSection />
      <Footer />
    </main>
  );
}
